<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p> Dear {{$data['name']}},</p>
<p> Please use the link below to download your Buying Guide copy.</p>
@if(!empty($data['buying']))
    <a href="{!! $data['buying'] !!}" target="_blank">Download Buying Guide</a>
@endif
<p style="font-size: x-small">
    Please do not reply directly to this autogenerated email message. If you have any questions or concerns please contact <a href="https:multidynamicingleburn.com.au">Multi Dynamic Ingleburn Team</a>
</p>
</body>
</html>