<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p> Dear {{$data['name']}},</p>
<p> Please use the link below to download your Selling Guide copy.</p>
@if(!empty($data['selling']))
<a href="{!! $data['selling'] !!}" target="_blank">Download Selling Guide</a>
@endif
<p style="font-size: x-small">
    Please do not reply directly to this autogenerated email message. If you have any questions or concerns please contact <a href="https:auburn.multidynamic.com.au">Multi Dynamic Auburn Team</a>
</p>
</body>
</html>